version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build image
      - run:
          name: Build docker image 
          command: |
            docker info
            docker build -t bjpadhy/colloquy:latest .
      # push image
      - run:
          name: Push image to heroku container registry 
          command: |
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag bjpadhy/colloquy:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
  deploy:
    machine: true
    steps:
      - checkout
      # setup heroku cli
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.sh
      # deploy image to heroku
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:release web --app $HEROKU_APP_NAME
orbs:
  jira: circleci/jira@1.2.2
workflows:
  main:
    jobs:
    - build:
        filters:
          branches:
            only: master
        post-steps: 
          - jira/notify:
              environment_type: production
              job_type: build
    - deploy:
        requires:
          - build
        filters:
            branches:
              only: master
        post-steps:
          - jira/notify:
              environment_type: production
              job_type: deployment
